### ISSUE TITLE
Watch face

### ISSUE THREAD

**Issue by icedman** [rogerdahl/uwatch2-client#3]
Is Watchface binary upload possible?
Kabbi has some of the official ones on his Watchface parser repo. https://github.com/kabbi/uwatchfaces

**Comment by rogerdahl** [comment]
Not supported, sorry. If you find a description of the binary protocol for it, I'll certainly consider adding it!

**Comment by icedman** [comment]
That's ok. 
The description for data upload is in kabbi's gist. I was able to upload a watchface following his example.  Hit or miss though - sometimes the watchface gets updated, most of the time it doesn't. I'll just buy a sniffer to investigate myself.
