### ISSUE TITLE
Code for weather

### ISSUE THREAD

**Issue by devmarxx** [rogerdahl/uwatch2-client#4]
First thank you for your great project.

Today I got my P8b and was able to set the time due to your great python code here.

I played a bit with the weather and this code gives weather information to the watch:

`    # Weather

    def set_future_weather(self, args=None):
        """Set future weather
        Args 21 bytes from C2439F
        Returns ?
        tested_and_working: False
    """
        return self._send_raw_cmd(0x42,"BBBBBBBBBBBBBBBBBBBBB",0,1,8,0,0,6,0,253,5,0,255,6,3,2,10,3,5,11,0,4,11)

    def set_today_weather(self, args=None):
        """Set today weather
        Args variable length from C2439F
        Returns ?
        tested_and_working: False
    """
        return self._send_raw_cmd(0x43,"BBBBBBBBBBBBBBBBBBBBBBB",0,0,4,0,32,0,32,0,32,0,32,0,110,0,117,0,108,0,108,0,77,0,6)`

Now we "only" need to find out which byte means what :-)

Regards

Chris

**Comment by devmarxx** [comment]
I did some tests on the weather bytes:

Today (First Byte D0):

(0x43,"BBBBBBBBBBBBBBBBBBBBBBB",0,0,4,0,32,0,32,0,32,0,32,0,110,0,117,0,108,0,108,0,77,0,6)

Future (First Byte D0):

(0x42,"BBBBBBBBBBBBBBBBBBBBB",0,1,8,0,0,6,0,253,5,0,255,6,3,2,10,3,5,11,0,4,11)

Home screen:

Temperature  range Future D1-D2
Icon Today D1

Weather screen:

Temperature Today D2
Icon Today D1
Temperature range Future D1-D2
Tomorrow Future D4-D5

Week screen (DAYS after tomorrow):

DAY1 temperature range Future D7-D8 Icon Future D6
DAY2 temperature range Future D10-D11 Icon Future D9
DAY3 temperature range Future D13-D14 Icon Future D12
DAY4 temperature range Future D15-D16 Icon Future D14

Temperatures: 255 is -1, 254 is -2, ...

Icons:

0 Cloud with sun
1 Fog
2 Cloud
3 Cloud with heavy rain
4 Cloud with rain
5 Sun
6 ?
7 ?

So next step is writing a nice little script that fetches the local weather from OpenWeatherMao and writes the parameters to the watch.

Chris

**Comment by devmarxx** [comment]
Here my working p8 weather script:

https://github.com/devmarxx/p8_weather.py

Enjoy :-)

Greetinx

Chris

**Comment by rogerdahl** [comment]
Awesome! I'd be happy to accept a pull request. If you feel like it, you could turn the section that is repeated for each day into a function. Importing the library instead of launching the client would be nice as well. Then you could generate the data as a tuple or list instead of as a comma separate string.

**Comment by devmarxx** [comment]
Thanx :-)

I wrote the weather functionality as an extra script, because the weather information can be provided by different platforms. I use 7timer.info, because no api key is needed. Other platforms like i.e. openweathermap are more accurate and will be a better choice for many users.

I would keep the weather functionality separated from the rest of the code, so other scripts can come up (for i.e. openweathermap). 

I think, the only thing what needs to be done in your code is set this code (or similar) in uwatch2lib.py:

`def set_future_weather(self, args):
       arr = args.split(',')
       return self._send_raw_cmd(0x42,"BBBBBBBBBBBBBBBBBBBBB",*arr)

   def set_today_weather(self, args):
       arr = args.split(',')
       return self._send_raw_cmd(0x43,"BBBBBBBBBBBBBBBBBBBBBBB",*arr)`

Perhaps you can do that?

I agree that it is not pretty to send a comma separated string via the command line, but from my point of view it keeps the weather scripting more general.

But I could be wrong of course :-)

Greetinx

Chris

**Comment by rogerdahl** [comment]
Yes, the code related to 7timer.info should definitely stay separate. If we were to make the changes you suggest, everyone would have to create comma separated strings in order to use the weather functions in the library. I'll make the changes I was thinking of, and add a note in your repo. Thanks again :)
